language: node_js
node_js:
  - "4.2"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8


before_script:
  - npm run unit

script:
  - npm run build

cache:
  directories:
    - node_modules
