export const ADD_TO_TEAM = 'ADD_TO_TEAM'
export const LOAD_EVENT = 'LOAD_EVENT'
export const JOIN_TEAM_SUCCESS = 'JOIN_TEAM_SUCCESS'
export const JOIN_TEAM_DECLINED = 'JOIN_TEAM_DECLINED'
export const RECEIVE_NOTIFICATIONS = 'RECEIVE_NOTIFICATIONS'
export const INCREASE_TEAMSIZE = 'INCREASE_TEAMSIZE';
export const DECREASE_TEAMSIZE = 'DECREASE_TEAMSIZE'
export const ADD_JOIN_REQUEST = 'ADD_JOIN_REQUEST'
